[build]
  command = "npm run build:main"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"